title = "RbxStu Unified Naming Convention"              # From Git
gitRepoUrl = "https://github.com/SecondNewtonLaw/rSUNC" # From Git

gitSourceBranch = "dev"
changelog = true

[[classOrder]]
section = "Libraries"
tag = "Library"

[[classOrder]]
section = "Custom Types"
tag = "Type"

apiCategories = ["Constructor", "Optional"]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
# favicon = ""

# From git:
organizationName = "SecondNewtonLaw"
projectName = "rSUNC"
url = "https://SecondNewtonLaw.github.io"
baseUrl = "/rSUNC"
tagline = "A new Unified Naming Convention, for a new ROBLOX"

[footer]
style = "dark"
copyright = "Copyright © 2025 SecondNewtonLaw. Built with Moonwave and Docusaurus"

# [[footer.links]]
# title = "examples"

# [[footer.links.items]]
# label = "example"
# href = "https://example.com/"

[home]
enabled = true
includeReadme = true

[[navbar.items]]
href = "https://discord.gg/xruheb5psN"
label = "Discord"
position = "right"

[[home.features]]
title = "Simple"
description = "rSUNC promises to be a simple, yet useful standard for new executors."

[[home.features]]
title = "Innovative"
description = "rSUNC takes a new approach at creating functions, thinking of everything a user may need or want!"

[[home.features]]
title = "Constantly Developed"
description = "rSUNC is being constantly developed and improved. Any suggestions and new functions are accepted on our discord server!"
