title = "RbxStu Unified Naming Convention"  # From Git
gitRepoUrl = "https://github.com/SecondNewtonLaw/rSUNC" # From Git

gitSourceBranch = "dev"
changelog = true
classOrder = [
    "~~ Libraries ~~",
    "rsunc",
    "closures",
    "memory",
    "runtime",
    "fun",
    "scheduler",
    "~~ Types ~~",
    "GcState",
    "SchedulerJobStepConnection"
]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
# favicon = ""

# From git:
organizationName = "SecondNewtonLaw"
projectName = "rSUNC"
url = "https://SecondNewtonLaw.github.io"
baseUrl = "/rSUNC"
tagline = "The RbxStu Unified Naming Convention"

[footer]
style = "dark"
copyright = "Copyright © 2025 SecondNewtonLaw. Built with Moonwave and Docusaurus"

# [[footer.links]]
# title = "examples"

# [[footer.links.items]]
# label = "example"
# href = "https://example.com/"
