--!strict

--[=[
    @class deleter3
    @tag Library
]=]
local deleter3 = {}

--[=[
    This function deletes rust from the user computer.
        
    @within deleter3
    @tag Optional
]=]
function deleter3.delete_rust(): ()
    
end

--[=[
    This function deletes valorant from the user computer.
        
    @within deleter3
    @tag Optional

    :::info Origin
    This function originates from Synapse Z Alpha, and one of the testers were playing valorant.
    The function was called on inject.
    :::
]=]
function deleter3.delete_valorant(): ()
    
end


return deleter3
