--!strict

--[=[
    @class fun
    @tag Library
]=]
local fun = {}

--[=[
    This function adds two balls to the LocalPlayer's character.
        
    @within fun
    @tag Optional

    :::info Origin
    This function originates from Script-Ware V2, and was meant as a fun addition and it is not tested for rSUNC.
    :::
]=]
function fun.balls(): ()
    
end

--[=[
    This function adds two furry balls to the LocalPlayer's character.
        
    @within fun
    @tag Optional

    :::info Origin
    This function originates from Synapse Z extended balls library.
    :::
]=]
function fun.furryballs(): ()
    
end

--[=[
    This function adds two furry balls to the LocalPlayer's character.
        
    @within fun
    @tag Optional

    :::info Origin
    This function originates from Synapse Z extended balls library.
    :::
]=]
function fun.furryballs(): ()
    
end

--[=[
    This function adds two sigma balls to the LocalPlayer's character.
        
    @within fun
    @tag Optional

    :::info Origin
    This function originates from Synapse Z extended balls library.
    :::
]=]
function fun.sigmaballs(): ()
    
end

--[=[
    This function adds two woman (dishwasher) balls to the LocalPlayer's character.
        
    @within fun
    @tag Optional

    :::info Origin
    This function originates from Synapse Z extended balls library.
    :::
]=]
function fun.womanballs(): ()
    
end

--[=[
    This function adds two cat balls to the LocalPlayer's character.
        
    @within fun
    @tag Optional

    :::info Origin
    This function originates from Synapse Z extended balls library.
    :::
]=]
function fun.catballs(): ()
    
end

--[=[
    This function adds two custom balls to the LocalPlayer's character.
        
    @within fun
    @tag Optional

    @param asset_id string -- The roblox asset id to be rendered at the balls

    :::info Origin
    This function originates from Synapse Z extended balls library.
    :::
]=]
function fun.customballs(asset_id: string): ()
    
end

return fun
